// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXFI0CJ3QyJxV9y49zD9yX7bM5xMyMYX0',
    appId: '1:1047401755178:web:44d7e92c7236109d76c953',
    messagingSenderId: '1047401755178',
    projectId: 'squipapphackathon',
    authDomain: 'squipapphackathon.firebaseapp.com',
    storageBucket: 'squipapphackathon.appspot.com',
    measurementId: 'G-XC0VC5FSKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu_STuCpLSsQCvnJXbAhfz-5SLomapW2c',
    appId: '1:1047401755178:android:bf5ca914e97cfe0576c953',
    messagingSenderId: '1047401755178',
    projectId: 'squipapphackathon',
    storageBucket: 'squipapphackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7kG1JUs3pEJakKC4ZL8Jl4dWo-ft5Pa0',
    appId: '1:1047401755178:ios:09db38ec7985038576c953',
    messagingSenderId: '1047401755178',
    projectId: 'squipapphackathon',
    storageBucket: 'squipapphackathon.appspot.com',
    iosClientId: '1047401755178-j3tbic23atahn57oeku0qmgncn8ak6m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.squipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7kG1JUs3pEJakKC4ZL8Jl4dWo-ft5Pa0',
    appId: '1:1047401755178:ios:09db38ec7985038576c953',
    messagingSenderId: '1047401755178',
    projectId: 'squipapphackathon',
    storageBucket: 'squipapphackathon.appspot.com',
    iosClientId: '1047401755178-j3tbic23atahn57oeku0qmgncn8ak6m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.squipApp',
  );
}
